development:
  adapter: postgresql
  encoding: unicode
  database: kkubby_development
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: ryanbuckley
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: kkubby_test
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: ryanbuckley
  password: